build:
    environment:
        php:
            version: 7.2
        postgresql: false
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
checks:
    php: true

filter:
    excluded_paths:
        - "tests/*"
        - "vendor/*"
